# Generated by Django 4.1 on 2022-08-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_pizza_name_pizza_pizza_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_name',
            new_name='Pizza_name',
        ),
    ]
